apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: mysql
    purpose: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      purpose: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        purpose: expense
    spec:
      containers:
      - name: mysql
        image: usha43/deployment:1.0.0
